# Homework 1: Transition from NumPy to PyTorch

Name: Michael Dang

Email: ld8np@umsystem.edu

Partner Name(s) (if applicable): Karthik Chellamuthu

Partner Email(s) (if applicable):

### Submission instructions

- Submit the modified python notebook as homework submission.
- Group submission is enabled, you can submit this coding assignment with up to 2 teammates in our class. For instruction of how to do a group submission. Please refer to Canvas useful links.
- You can google answers on StackOverflow, please attach the corresponding StackOverflow answer as comments. However, if the answer is converted to `torch` format, no credit will be awarded.
- You can ask answer in Large Language Model-based software such as Co-Pilot or ChatGPT. However, your code has to be runnable.
- Do not change the number of cells! Please work in the cell provided. If you need extra cells for debugging and testing purposes, we can work at the end of this notebook, save everything as a backup for review, and delete the extra cells in the submitted version.





### Instructions
Do **not** use for loops in any of our solutions! For example if a problem asks us generate an array from 0 to 9: then
```python
x = []
for i in range(10):
    x.append(i)
```
this will only result a partial credit while
```python
x = np.arange(10)
```
or
```python
x = torch.arange(10)
```
will yield a full score.

### Problems
Below are 6 problems that explore different common used tools in Numpy and how to translate them into Torch codes. Each problem gives examples demonstrating the concept and has an associated coding task. Complete the coding tasks for credit.

### Grading
This homework has 6 problems, 5 points each. The homework will be graded based on completion (successfully run all the code cells) and the grade counts towards your course grade. The homework will weigh 50% compared to the subsequent assignemnts (it's not fully weighted...).




## Coding environments and submission
If we do not have `torch` installed on your computer, we have three ways to upload this notebook to [Google colab](https://colab.research.google.com/)：

1. Open up Google Colab, choose `Upload` to upload this template and work there. After we have done working we can select `File->Download .ipynb`.
2. Open up Google Colab, choose either `GitHub` or `Google Drive` to select the uploaded notebook in the corresponding website. After done working, we can sync the file to the corresponding GitHub or Google Drive copy.

In [ ]:
# Run Me First
import torch

## 1D Basic Array Functions
### Examples

In [ ]:
arr1 = torch.tensor([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [ ]:
# Accessing elements
print(arr1[0])
print(arr1[3])

tensor(55.7000)
tensor(75.7000)


In [ ]:
#Slicing: syntax is start:end:step, all are optional for compatibility
print(arr1[0:3]) # arr[0], arr[1], arr[2], non-inclusive of the ending index
print(arr1[:3]) # if the start is emtpy start = 0, this is the same with arr[0:3]
print(arr1[17:]) # if the end is emtpy, then this is accessing arr1[17], ..., till, the last entry of arr1
print(arr1[:]) # no start nor end, print all arr1

tensor([55.7000, 51.4000, 50.5000])
tensor([55.7000, 51.4000, 50.5000])
tensor([58.4000, 70.4000, 41.2000])
tensor([55.7000, 51.4000, 50.5000, 75.7000, 58.4000, 40.1000, 61.5000, 57.1000,
        60.9000, 66.6000, 60.4000, 68.1000, 66.9000, 53.4000, 48.6000, 56.8000,
        71.6000, 58.4000, 70.4000, 41.2000])


In [ ]:
#Element Types
print(arr1.dtype)
print(torch.tensor([0, 1, 2, 3]).dtype)
print(torch.tensor([1.0, 1.5, 2.0, 2.5]).dtype)
print(torch.tensor([1.0, 1.5, 2.0, 2.5], dtype=torch.float64).dtype)
print(torch.tensor([True, False, True]).dtype)

torch.float32
torch.int64
torch.float32
torch.float64
torch.bool


In [ ]:
# Looping - AVOID THIS!

for i in range(len(arr1)):
    element = arr1[i]
    print(f'Array {i}-th entry has value {element}')

Array 0-th entry has value 55.70000076293945
Array 1-th entry has value 51.400001525878906
Array 2-th entry has value 50.5
Array 3-th entry has value 75.69999694824219
Array 4-th entry has value 58.400001525878906
Array 5-th entry has value 40.099998474121094
Array 6-th entry has value 61.5
Array 7-th entry has value 57.099998474121094
Array 8-th entry has value 60.900001525878906
Array 9-th entry has value 66.5999984741211
Array 10-th entry has value 60.400001525878906
Array 11-th entry has value 68.0999984741211
Array 12-th entry has value 66.9000015258789
Array 13-th entry has value 53.400001525878906
Array 14-th entry has value 48.599998474121094
Array 15-th entry has value 56.79999923706055
Array 16-th entry has value 71.5999984741211
Array 17-th entry has value 58.400001525878906
Array 18-th entry has value 70.4000015258789
Array 19-th entry has value 41.20000076293945


In [ ]:
# (Almost) Every numpy functions has it torch counterparts
print(arr1.mean())
print(arr1.std())
print(arr1.max())
print(arr1.sum())
print()
print(torch.mean(arr1))
print(torch.std(arr1))
print(torch.min(arr1))
print(torch.sum(arr1))

tensor(58.6850)
tensor(9.5809)
tensor(75.7000)
tensor(1173.7001)

tensor(58.6850)
tensor(9.5809)
tensor(40.1000)
tensor(1173.7001)


### Problem 1

Fill in the following cell to calculate the maximum of the first half (first `len(arr1)//2` elements) and the second half of the array using slicing and the built-in `max()` method.

In [ ]:
max_1st_half = max(arr1[:len(arr1)//2])      # Replace this None with your code
max_2nd_half = max(arr1[len(arr1)//2:])        # Replace this None with your code

# your code here

print(f"Max of the 1st half: {max_1st_half}; Max of the 2nd half: {max_2nd_half}")

# expected output: Max of the 1st half: 75.69999694824219; Max of the 2nd half: 71.5999984741211


Max of the 1st half: 75.69999694824219; Max of the 2nd half: 71.5999984741211


## 1D Arithmetic and Logic
### Examples

In [ ]:
# Arithmetic operations between 2 torch tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([1, 2, 1, 2])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b) # this compute a[i]**b[i] for each i, where ** is the exponential operator

tensor([2, 4, 4, 6])
tensor([0, 0, 2, 2])
tensor([1, 4, 3, 8])
tensor([1., 1., 3., 2.])
tensor([ 1,  4,  3, 16])


In [ ]:
# Arithmetic operations between a torch tensor and a single number
a = torch.tensor([1, 2, 3, 4])
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([ 1,  4,  9, 16])


In [ ]:
# Logical operations with torch tensors
a = torch.tensor([True, True, False, False])
b = torch.tensor([True, False, True, False])

print(a & b)
print(a | b)
print(~a)

print(a & True)
print(a & False)

print(a | True)
print(a | False)

tensor([ True, False, False, False])
tensor([ True,  True,  True, False])
tensor([False, False,  True,  True])
tensor([ True,  True, False, False])
tensor([False, False, False, False])
tensor([True, True, True, True])
tensor([ True,  True, False, False])


In [ ]:
# Comparison operations of torch tensors to a number
a = torch.tensor([1, 2, 3, 4])
b = 2

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)

tensor([False, False,  True,  True])
tensor([False,  True,  True,  True])
tensor([ True, False, False, False])
tensor([ True,  True, False, False])
tensor([False,  True, False, False])
tensor([ True, False,  True,  True])


### Problem 2
Fill in this section to compute a `torch.tensor` containing the average of the two given arrays to achieve the effect of the following `for` loop:
```python
arr_avg = []
for i in range(len(arr1)):
    arr_avg.append((arr1[i].item() + arr2[i].item())/2)
print(arr_avg)
```
You can test the output of this print by copy and paste this snippet to a new cell.

In [ ]:
arr1 = torch.tensor([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

arr2 = torch.tensor([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

'''

'''
arr_avg = (torch.add(arr1, arr2))/2   # Replace this with your code

# your code here

print(arr_avg)

# expected output:
# tensor([ 96.4160, 102.6443, 101.4113,  93.3163, 103.4556,  98.1482, 102.3511,
#          91.7785,  92.8355,  89.6558,  99.2187,  98.4843,  94.1728, 117.3351,
#          98.2756,  33.0404,  41.9052,  90.9630,  57.0840,  93.0602])

tensor([ 96.4160, 102.6443, 101.4113,  93.3163, 103.4556,  98.1482, 102.3511,
         91.7785,  92.8355,  89.6558,  99.2187,  98.4843,  94.1728, 117.3351,
         98.2756,  33.0404,  41.9052,  90.9630,  57.0840,  93.0602])


## 1D Boolean (Fancy and Fast) Indexing
###  Examples

In [ ]:
# Using index arrays
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([True, True, False, False])

print(a[b])
print(a[torch.tensor([True, False, True, False])]) # this returns the 1st (a[0]) and the 3rd (a[2]) element of a

tensor([1, 2])
tensor([1, 3])


In [ ]:
# Creating the index array using vectorized operations (Recall ReLU implemented in class)
a = torch.tensor([1, 2, 3, 2, 1])
b = (a >= 2)

print(a[b])
print(a[a >= 2])

tensor([2, 3, 2])
tensor([2, 3, 2])


In [ ]:
# Creating the index array using vectorized operations on another array
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([1, 2, 3, 2, 1])

print(b == 2)
print(a[b == 2])

tensor([False,  True, False,  True, False])
tensor([2, 4])


### Problem 3

Fill in the following cell using the boolean indexing vectorization technique to calculate an array that can be achieved using the following `for` loop:
```python
result = []
for i in range(len(arr1)):
    if arr1[i] < 60:
        result.append(arr2[i].item())

```

In [ ]:
arr1 = torch.tensor([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

arr2 = torch.tensor([4,   5,  37,   3,  12,
                 4,  35,  38,   5,  37,
                 3,   3,  68,  38,  98,
                 2, 249,   2, 127,  35])

'''

'''
result = arr2[arr1<60] # Replace this with your code

# your code here

print(result)

# expected output
# tensor([  4,   5,   3,  12,   4,  35,  38,  37,   3,   3,  68,   2, 249,   2,
#         127,  35])


tensor([  4,   5,   3,  12,   4,  35,  38,  37,   3,   3,  68,   2, 249,   2,
        127,  35])


## 2D Basic Functions: Indexing, Axis
### Example 1

In [ ]:
mat1 = torch.tensor([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [ ]:
# Accessing elements
print(mat1[1, 3]) # 2nd row (index 1, or row 1), 4th col (index 3, or row 3)
print(mat1[1:3, 3:5]) # row 1 to row 3 (not included), col 3 to col 5 (not included)
print(mat1[1, :]) # what is this?

tensor(2328)
tensor([[2328, 2539],
        [6461, 2691]])
tensor([1478, 3877, 3674, 2328, 2539])


In [ ]:
# Vectorized operations on rows or columns
print(mat1[0, :] + mat1[1, :])
print(mat1[:, 0] + mat1[:, 1])

tensor([1478, 3877, 3676, 2333, 2539])
tensor([   0, 5355, 5701, 4952, 6410, 5509,  324,    2, 5223, 5385])


In [ ]:
# Vectorized operations on entire arrays
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
b = torch.tensor([[1, 1, 1],
                  [2, 2, 2],
                  [3, 3, 3]])
print(a + b)

tensor([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]])


### Example 2

In [ ]:
# torch dim argument
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(a.shape) # dim 0 is 4 (rows), dim 1 is 3 (cols)
print(a.sum())
print(a.sum(dim=0)) # dim = 0 means the dim 0 is the dimension to reduce, dim 1 is left, the output is a length 3 array, which is the column sum
print(a.sum(dim=1)) # this is row sum, since the column dimension is reduced

torch.Size([4, 3])
tensor(78)
tensor([22, 26, 30])
tensor([ 6, 15, 24, 33])


### Problem 4


Fill in the following cell to achieve the effect of the `for` for the array `mat1` below, store the maximum entry of each row of `mat1`:

```python
mat1 = [[   0,    0,    2,    5,    0],
        [1478, 3877, 3674, 2328, 2539],
        [1613, 4088, 3991, 6461, 2691],
        [1560, 3392, 3826, 4787, 2613],
        [1608, 4802, 3932, 4477, 2705],
        [1576, 3933, 3909, 4979, 2685],
        [  95,  229,  255,  496,  201],
        [   2,    0,    1,   27,    0],
        [1438, 3785, 3589, 4174, 2215],
        [1342, 4043, 4009, 4665, 3033]]
row_max = []
for row in mat1:
    row_max.append(max(row))
```

Note the simplest way is to use the `torch.max()` with an argument `dim=`

In [ ]:
mat1 = torch.tensor([[   0,    0,    2,    5,    0],
        [1478, 3877, 3674, 2328, 2539],
        [1613, 4088, 3991, 6461, 2691],
        [1560, 3392, 3826, 4787, 2613],
        [1608, 4802, 3932, 4477, 2705],
        [1576, 3933, 3909, 4979, 2685],
        [  95,  229,  255,  496,  201],
        [   2,    0,    1,   27,    0],
        [1438, 3785, 3589, 4174, 2215],
        [1342, 4043, 4009, 4665, 3033]])

row_max = torch.max(mat1, dim = 1)          # Replace this with your code

print(row_max)

# expected output: tensor([   5, 3877, 6461, 4787, 4802, 4979,  496,   27, 4174, 4665])

torch.return_types.max(
values=tensor([   5, 3877, 6461, 4787, 4802, 4979,  496,   27, 4174, 4665]),
indices=tensor([3, 1, 3, 3, 1, 3, 3, 3, 3, 3]))


### Problem 5

Fill in the following cell to achieve the effect of the `for` for the array `mat1` above, store the index of the maximum entry of each row of a list version of `mat1`:

```python
mat1 = [[   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]]
index_max = []
for row in mat1:
    tmp = row.index(max(row))
    index_max.append(index_max)
```

Hint: the function `argmax()` in PyTorch may be helpful: https://pytorch.org/docs/stable/generated/torch.argmax.html, which can be either applied as a function or as a method for the tensor `a.argmax()` with an `dim=` argument.

Hint2: with the PyTorch 2.0, `max()` now returns indices as well:  https://pytorch.org/docs/stable/generated/torch.max.html.

In [ ]:
index_max = torch.argmax(mat1, dim = 1) # Replace this with your code

print(index_max)

# expected output: tensor([3, 1, 3, 3, 1, 3, 3, 3, 3, 3])

tensor([3, 1, 3, 3, 1, 3, 3, 3, 3, 3])


## Runtime Comparison

In [ ]:
import time

We will need to be able to generate random numbers for hte next problem. `PyTorch` also all sorts of random number generator similar to `numpy.random` submodule.

We can use `?` to access the documentation of every function, so keep it in mind for easy access to documentations! If we are in Colab or Visual Studio Code, hovering the mouse over a function pops up the documentation as well.

In [ ]:
?torch.randn


### Problem 6

Using `torch.randn` function, which takes in inputs `(n,m)`, to generate a random 2d array of `n` rows and `m` columns.

Note: we should format the code as `torch.randn((2,5))` not `torch.randn(2,5)` if we want to generate a 2 by 5 random matrix.

In [ ]:

def calculate_row_sums_loop(arr):
    """
    Fill in this function to calculate row sums of 2d_array using a for loop.
    """
    result = []
    # for row in arr:
    #   sum_of_each_row = 0
    #   for value in row:
    #     sum_of_each_row += value


    # return result.append(sum_of_each_row)


# More robust
    for row in arr:
      return result.append(sum(row))

In [ ]:
def calculate_row_sums_vec(arr):
    """
    Fill in this function to calculate row sums of 2d_array
    using pytorch builtin vectorized functions.
    """
    # your code here
    result = torch.sum(arr, 1)
    return result

After you done with the functions above, run this to compare runtime of for loops and numpy functions. Play with the matrix dimesions to see the effect!

Hint: for the non-vectorized function it should take longer.

In [ ]:
# generate a random 2d array
num_rows = 100000
num_cols = 100
random_2d_array = torch.randn((num_rows, num_cols))

start = time.time()
# calculate row sums by for loop
calculate_row_sums_loop(random_2d_array)
end = time.time()
print(f"loop: {end - start} secs.")

start = time.time()
# calculate row sums by for np.sum
calculate_row_sums_vec(random_2d_array)
end = time.time()
print(f"vectorized: {end - start} secs.")

loop: 0.4026648998260498 secs.
vectorized: 0.005869626998901367 secs.


In [ ]:
# extra cell